apiVersion: v1
kind: Secret
metadata:
  name: dbcp-entry-service-secret
  namespace: default
  labels:
    app.kubernetes.io/name: dbcp-entry-service
type: Opaque
stringData:
  DBCP_TARGET_DB: "go_entry_app:699432ca2d1a5729950965a32465e4028126de27f237142a@tcp(host.docker.internal:3306)/go_entry_user_mgmt?charset=utf8mb4&parseTime=true&loc=Local"
  DBCP_TARGET_REDIS: "host.docker.internal:6379"
  APP_TOKEN_SECRET: "bbdbbc7f5b9f202b3ee33dfa2b57a6c4c7486c78e0c77798637713fb06fba214"
  APP_REDIS_PASSWORD: ""

