apiVersion: v1
kind: Secret
metadata:
  name: dbcp-entry-service-secret
  namespace: default
  labels:
    app.kubernetes.io/name: dbcp-entry-service
type: Opaque
stringData:
  DBCP_TARGET_DB: "go_entry_app:<password>@tcp(host.docker.internal:3306)/go_entry_user_mgmt?charset=utf8mb4&parseTime=true&loc=Local"
  DBCP_TARGET_REDIS: "host.docker.internal:6379"
  APP_TOKEN_SECRET: "<64-hex-chars>"
  APP_REDIS_PASSWORD: ""
