apiVersion: dbcp.shopee.io/v1alpha1
kind: DbcpEntryService
metadata:
  name: dbcp-entry-service
  namespace: entry-system
spec:
  config:
    targetDB: "go_entry_app:123456@tcp(10.31.4.27:3306)/go_entry_user_mgmt?charset=utf8mb4&parseTime=true&loc=Local"
    targetRedis: "10.31.4.27:6379"
    serviceExportPort: 8080
  service:
    image: "dbcp-entry-service:local"
    replicas: 2
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

