apiVersion: v1
kind: ServiceAccount
metadata:
  name: dbcp-entry-controller
  namespace: default
  labels:
    app.kubernetes.io/name: dbcp-entry-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbcp-entry-controller
  labels:
    app.kubernetes.io/name: dbcp-entry-controller
rules:
  - apiGroups:
      - dbcp.shopee.io
    resources:
      - dbcp-entry-services
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - dbcp.shopee.io
    resources:
      - dbcp-entry-services/finalizers
    verbs:
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dbcp-entry-controller
  labels:
    app.kubernetes.io/name: dbcp-entry-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dbcp-entry-controller
subjects:
  - kind: ServiceAccount
    name: dbcp-entry-controller
    namespace: default
