error_log /Users/duwei.sun/Desktop/go_entry_task/runtime/nginx/error.log notice;
pid /Users/duwei.sun/Desktop/go_entry_task/runtime/nginx/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /usr/local/etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /Users/duwei.sun/Desktop/go_entry_task/runtime/nginx/access.log;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 8080;
        server_name localhost;
        root /Users/duwei.sun/Desktop/go_entry_task/web/static;
        index index.html;

        location /api/ {
            proxy_pass http://127.0.0.1:8081;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /profile-pictures/ {
            alias /Users/duwei.sun/Desktop/go_entry_task/runtime/profile-pictures/;
        }
    }
}
