#!/usr/bin/env bash
set -euo pipefail

ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD:-123456}"
APP_DB_NAME="${APP_DB_NAME:-go_entry_user_mgmt}"
APP_DB_USER="${APP_DB_USER:-go_entry_app}"
APP_DB_PASSWORD="${APP_DB_PASSWORD:-699432ca2d1a5729950965a32465e4028126de27f237142a}"

mysql --protocol=TCP -h127.0.0.1 -P3306 -uroot "-p${ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS ${APP_DB_NAME}
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE USER IF NOT EXISTS '${APP_DB_USER}'@'localhost'
  IDENTIFIED BY '${APP_DB_PASSWORD}';
ALTER USER '${APP_DB_USER}'@'localhost'
  IDENTIFIED BY '${APP_DB_PASSWORD}';

CREATE USER IF NOT EXISTS '${APP_DB_USER}'@'127.0.0.1'
  IDENTIFIED BY '${APP_DB_PASSWORD}';
ALTER USER '${APP_DB_USER}'@'127.0.0.1'
  IDENTIFIED BY '${APP_DB_PASSWORD}';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, ALTER
  ON ${APP_DB_NAME}.*
  TO '${APP_DB_USER}'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, ALTER
  ON ${APP_DB_NAME}.*
  TO '${APP_DB_USER}'@'127.0.0.1';

FLUSH PRIVILEGES;
SQL

echo "MySQL database and application user are ready."

